### PR TITLE
feat: Add support for PHP 8.0

### PR DESCRIPTION
**Pull request by owenconti**

### CODE REVIEW

**Comment by peter279k** [comment]
Thanks!

**Comment by digilist** [comment]
Would it be possible to tag a new version with the PHP 8 support? :blush:

**Comment by galengidman** [comment]
+1 on tagging and releasing this as soon as possible. Thanks!

**Comment by peter279k** [comment]
@digilist and @galengidman, it's released for [v1.0.3](https://github.com/mexitek/phpColors/releases/tag/v1.0.3).

Sorry for my delay response!

**Comment by galengidman** [comment]
@peter279k Thank you so much, really appreciate it.

**Comment by digilist** [comment]
Many thanks from me as well :blush:

**Pull request merged**
